// Instrument Presets for Synthesizer
// These presets are based on real musical instruments and can be added to the main PRESETS object

export const INSTRUMENT_PRESETS = {
  // 🎹 PIANO & KEYBOARD PRESETS
  'grand-piano': {
    name: 'grand-piano',
    waveform: 'sine' as const,
    volume: 50,
    attack: 9,
    release: 25,
    detune: 0,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 6000,
    filterResonance: 0.3,
    compressionEnabled: true,
    compressionThreshold: -20,
    compressionRatio: 2.5,
    compressionAttack: 0.01,
    compressionRelease: 0.1
  },
  'upright-piano': {
    name: 'upright-piano',
    waveform: 'sine' as const,
    volume: 45,
    attack: 10,
    release: 30,
    detune: 1,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 4500,
    filterResonance: 0.4
  },
  'rhodes-piano': {
    name: 'rhodes-piano',
    waveform: 'triangle' as const,
    volume: 47,
    attack: 12,
    release: 35,
    detune: 2,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.3,
    lfoDepth: 4,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 3800,
    filterResonance: 0.6,
    chorusEnabled: true,
    chorusRate: 0.7,
    chorusDepth: 0.003,
    chorusMix: 0.4
  },
  'wurlitzer-piano': {
    name: 'wurlitzer-piano',
    waveform: 'square' as const,
    volume: 49,
    attack: 11,
    release: 28,
    detune: 3,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.4,
    lfoDepth: 5,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 4200,
    filterResonance: 0.5
  },
  'clavinet': {
    name: 'clavinet',
    waveform: 'square' as const,
    volume: 53,
    attack: 8,
    release: 20,
    detune: 0,
    reverb: 'off' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'highpass' as const,
    filterFrequency: 800,
    filterResonance: 1,
    compressionEnabled: true,
    compressionThreshold: -15,
    compressionRatio: 3,
    compressionAttack: 0.01,
    compressionRelease: 0.08
  },

  // 🎸 GUITAR PRESETS
  'acoustic-guitar': {
    name: 'acoustic-guitar',
    waveform: 'sine' as const,
    volume: 58,
    attack: 8,
    release: 40,
    detune: 2,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.2,
    lfoDepth: 3,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 3500,
    filterResonance: 0.6
  },
  'electric-guitar-clean': {
    name: 'electric-guitar-clean',
    waveform: 'square' as const,
    volume: 47,
    attack: 12,
    release: 25,
    detune: 3,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.3,
    lfoDepth: 4,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 4000,
    filterResonance: 0.5
  },
  'electric-guitar-overdrive': {
    name: 'electric-guitar-overdrive',
    waveform: 'square' as const,
    volume: 55,
    attack: 10,
    release: 20,
    detune: 4,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.5,
    lfoDepth: 6,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 2800,
    filterResonance: 1.0,
    distortionEnabled: true,
    distortionAmount: 0.4,
    distortionType: 'soft' as const
  },
  'electric-guitar-distortion': {
    name: 'electric-guitar-distortion',
    waveform: 'sawtooth' as const,
    volume: 60,
    attack: 9,
    release: 18,
    detune: 1,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.6,
    lfoDepth: 8,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 2500,
    filterResonance: 1.2,
    distortionEnabled: true,
    distortionAmount: 0.6,
    distortionType: 'hard' as const
  },
  'bass-guitar': {
    name: 'bass-guitar',
    waveform: 'square' as const,
    volume: 57,
    attack: 8,
    release: 50,
    detune: 0,
    reverb: 'off' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 250,
    filterResonance: 1,
    compressionEnabled: true,
    compressionThreshold: -12,
    compressionRatio: 4,
    compressionAttack: 0.01,
    compressionRelease: 0.15
  },

  // 🥁 DRUM & PERCUSSION PRESETS
  'kick-drum': {
    name: 'kick-drum',
    waveform: 'sine' as const,
    volume: 45,
    attack: 12,
    release: 25,
    detune: 0,
    reverb: 'off' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 100,
    filterResonance: 1.5,
    compressionEnabled: true,
    compressionThreshold: -10,
    compressionRatio: 5,
    compressionAttack: 0.01,
    compressionRelease: 0.05
  },
  'snare-drum': {
    name: 'snare-drum',
    waveform: 'noise' as const,
    volume: 55,
    attack: 12,
    release: 20,
    detune: 0,
    reverb: 'off' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'bandpass' as const,
    filterFrequency: 800,
    filterResonance: 1.2,
    compressionEnabled: true,
    compressionThreshold: -15,
    compressionRatio: 3,
    compressionAttack: 0.01,
    compressionRelease: 0.08
  },
  'hi-hat': {
    name: 'hi-hat',
    waveform: 'noise' as const,
    volume: 45,
    attack: 8,
    release: 8,
    detune: 0,
    reverb: 'off' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'highpass' as const,
    filterFrequency: 8000,
    filterResonance: 1.5
  },
  'crash-cymbal': {
    name: 'crash-cymbal',
    waveform: 'noise' as const,
    volume: 50,
    attack: 12,
    release: 35,
    detune: 0,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'highpass' as const,
    filterFrequency: 6000,
    filterResonance: 0.8
  },
  'tom-tom': {
    name: 'tom-tom',
    waveform: 'sine' as const,
    volume: 50,
    attack: 8,
    release: 30,
    detune: 0,
    reverb: 'off' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 400,
    filterResonance: 1.2
  },

  // 🎺 BRASS & WOODWIND PRESETS
  'trumpet': {
    name: 'trumpet',
    waveform: 'sawtooth' as const,
    volume: 50,
    attack: 8,
    release: 35,
    detune: 2,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.4,
    lfoDepth: 5,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 3200,
    filterResonance: 0.8
  },
  'saxophone': {
    name: 'saxophone',
    waveform: 'triangle' as const,
    volume: 45,
    attack: 15,
    release: 50,
    detune: 1,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.4,
    lfoDepth: 3,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 2800,
    filterResonance: 0.6
  },
  'trombone': {
    name: 'trombone',
    waveform: 'sawtooth' as const,
    volume: 45,
    attack: 12,
    release: 45,
    detune: 1,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.3,
    lfoDepth: 4,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 2400,
    filterResonance: 0.7
  },
  'flute': {
    name: 'flute',
    waveform: 'sine' as const,
    volume: 55,
    attack: 15,
    release: 50,
    detune: 1,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.2,
    lfoDepth: 3,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 4000,
    filterResonance: 0.4
  },
  'clarinet': {
    name: 'clarinet',
    waveform: 'triangle' as const,
    volume: 42,
    attack: 18,
    release: 55,
    detune: 1,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.3,
    lfoDepth: 2,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 3000,
    filterResonance: 0.4
  },

  // 🎛️ SYNTHESIZER PRESETS
  'moog-synth': {
    name: 'moog-synth',
    waveform: 'sawtooth' as const,
    volume: 55,
    attack: 10,
    release: 25,
    detune: 2,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.8,
    lfoDepth: 5,
    lfoTarget: 'filter' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 2000,
    filterResonance: 1.2
  },
  'prophet-synth': {
    name: 'prophet-synth',
    waveform: 'square' as const,
    volume: 50,
    attack: 12,
    release: 30,
    detune: 4,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.6,
    lfoDepth: 8,
    lfoTarget: 'filter' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 2800,
    filterResonance: 1.5,
    chorusEnabled: true,
    chorusRate: 0.9,
    chorusDepth: 0.004,
    chorusMix: 0.5
  },
  'dx7-synth': {
    name: 'dx7-synth',
    waveform: 'sine' as const,
    volume: 45,
    attack: 12,
    release: 45,
    detune: 1,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.3,
    lfoDepth: 3,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 3200,
    filterResonance: 0.5
  },
  'juno-synth': {
    name: 'juno-synth',
    waveform: 'sawtooth' as const,
    volume: 53,
    attack: 11,
    release: 28,
    detune: 3,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.7,
    lfoDepth: 3,
    lfoTarget: 'filter' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 2400,
    filterResonance: 1.8,
    chorusEnabled: true,
    chorusRate: 0.8,
    chorusDepth: 0.005,
    chorusMix: 0.6
  },

  // 🎼 COMPOSITION TOOLS
  'metronome': {
    name: 'metronome',
    waveform: 'sine' as const,
    volume: 50,
    attack: 8,
    release: 5,
    detune: 0,
    reverb: 'off' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'highpass' as const,
    filterFrequency: 2000,
    filterResonance: 1.0
  },
  'tuning-fork': {
    name: 'tuning-fork',
    waveform: 'sine' as const,
    volume: 35,
    attack: 15,
    release: 50,
    detune: 0,
    reverb: 'off' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0,
    lfoDepth: 0,
    lfoTarget: 'pitch' as const,
    filterEnabled: true,
    filterType: 'bandpass' as const,
    filterFrequency: 440,
    filterResonance: 1.5
  },
  'drone': {
    name: 'drone',
    waveform: 'sine' as const,
    volume: 30,
    attack: 50,
    release: 100,
    detune: 0,
    reverb: 'on' as const,
    arpeggiator: 'off' as const,
    lfoRate: 0.1,
    lfoDepth: 5,
    lfoTarget: 'volume' as const,
    filterEnabled: true,
    filterType: 'lowpass' as const,
    filterFrequency: 800,
    filterResonance: 0.3
  }
};

// Instrument Documentation
export const INSTRUMENT_DOCS = {
  pianos: {
    grandPiano: 'Classical grand piano with rich harmonics and natural decay',
    uprightPiano: 'Warm upright piano sound with shorter sustain',
    rhodesPiano: 'Electric piano with bell-like tone and chorus effect',
    wurlitzerPiano: 'Vintage electric piano with warm, slightly distorted character',
    clavinet: 'Funky electric clavinet with sharp attack and high-pass filtering'
  },
  guitars: {
    acousticGuitar: 'Natural acoustic guitar with warm body resonance',
    electricGuitarClean: 'Clean electric guitar with subtle overtones',
    electricGuitarOverdrive: 'Overdriven electric guitar with moderate distortion',
    electricGuitarDistortion: 'Heavily distorted electric guitar for rock/metal',
    bassGuitar: 'Electric bass guitar with deep, punchy low end'
  },
  drums: {
    kickDrum: 'Deep kick drum with compression and low-frequency focus',
    snareDrum: 'Snappy snare drum with band-pass filtering',
    hiHat: 'Bright hi-hat with high-pass filtering for crisp attack',
    crashCymbal: 'Crash cymbal with natural decay and reverb',
    tomTom: 'Tunable tom-tom with medium decay and low-pass filtering'
  },
  brass: {
    trumpet: 'Bright trumpet with sawtooth waveform and moderate reverb',
    saxophone: 'Smooth saxophone with triangle waveform and warm tone',
    trombone: 'Rich trombone with sawtooth waveform and longer release'
  },
  woodwinds: {
    flute: 'Pure flute with sine waveform and long attack/release',
    clarinet: 'Warm clarinet with triangle waveform and moderate modulation'
  },
  synthesizers: {
    moogSynth: 'Classic Moog synthesizer with sawtooth and filter modulation',
    prophetSynth: 'Prophet synthesizer with square wave and chorus effect',
    dx7Synth: 'Digital DX7 synthesizer with sine wave and clean tone',
    junoSynth: 'Juno synthesizer with sawtooth, chorus, and filter modulation'
  },
  tools: {
    metronome: 'Click track for tempo reference',
    tuningFork: 'Pure A440 reference tone',
    drone: 'Sustained tone for harmonic reference'
  }
}; 